### ISSUE TITLE
Westeros Mod

### ISSUE THREAD

**Issue by Adri417** [WesterosCraft/WesterosBlocks#7]
Hello !
I have a question about the Westeros mod,
I use it in version 1.16.5 but I don't like the fact that it replaces the basic textures of the game.
Can I disable it?

**Comment by jacobgranberry** [comment]
Hi @Adri417 sorry for the very late reply - but for the 1.12 version you will have to fork and make the changes yourself.  When we release the 1.16.5 version the custom WesterosBlocks will not override any vanilla blocks
